### ISSUE TITLE
Instruções/documentação sobre configuração/setup

### ISSUE THREAD

**Issue by marcoonroad** [GSRios/Minibank#1]
Boa Tarde, man!

Estou encarregado do review/feedback do seu projeto aqui pelo time de Banking da Stone, e queria te pedir pra você documentar a configuração/instalação de dependências, por exemplo, o `flask_restful` usado nos arquivos de testes chamados `accountTests.py` e `clientTests.py`. É interessante também documentar como rodar o projeto.

Caso consiga adicionar persistência em banco com sucesso, seria muito legal da sua parte também documentar a configuração pro banco, por exemplo, no caso de migrações.

**Comment by marcoonroad** [comment]
A dependência `flask_restful` dos testes pode ser instalada sem problemas pelo `pip`, ao que parece, mas documentar sempre é bom caso você use outra forma de gerenciar dependências.

Uma boa ideia também é separar seus testes em uma pasta separada, por exemplo, chamada `test/`, `tests/` ou até `t/`.

**Comment by GSRios** [comment]
Boa tarde Marcos,

Tinha mencionado no email com a Renata que estava complementando a etapa do
BD e incluir todo o processo para rodar.

Assim que terminar essa parte posso entrar em contato contigo e te avisar?

Atenciosamente,
Mateus Santana Rios

Em 2 de fev de 2018 13:40, "Marco Aurélio" <notifications@github.com>
escreveu:

**Comment by GSRios** [comment]
To terminando a documentação.
Assim que concluir commito.

Desde já agradeço pelas sugestões.

Atenciosamente,
Mateus Santana Rios

Em 2 de fev de 2018 13:55, "Marco Aurélio" <notifications@github.com>
escreveu:

A dependência flask_restful dos testes pode ser instalada sem problemas
pelo pip, ao que parece, mas documentar sempre é bom caso você use outra
forma de gerenciar dependências.

Uma boa ideia também é separar seus testes em uma pasta separada, por
exemplo, chamada test/, tests/ ou até t/.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GSRios/Minibank/issues/1#issuecomment-362612777>, or mute
the thread

**Comment by marcoonroad** [comment]
Fechando pois não é mais da minha jurisdição as correções. Me desculpe por quaisquer inconveniências e transtornos.
